Volume revert to snapshot
eayunstack/cinder pull request #21
Opened 2017-08-18 09:58 UTC by wwba

volume-revert-to-snapshot

2017-09-04 07:19 UTC, zhaochao requested changes

2017-09-04 07:19 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        params = body['os-revert']
这里要检查一下 body 是不是合法（不包含 os-revert ） ，上游实现其实也有，但已经封装接口，直接当前版本其它的 action 里类似的代码。

2017-09-04 07:19 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        self.volume_api.revert_to_snapshot(context, volume, snapshot)
需要保持上游代码里捕获 self.volume_api.revert_to_snapshot 拋出的异常的代码。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/api.py
> +            self.db.snapshot_update(context, snapshot['id'],
更新数据库对象，可以不必特别捕获异常。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/api.py
> +            self.db.volume_update(context, volume['id'],
和上面相同，更新数据库对象，可以不必特别捕获异常。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/drivers/lvm.py
> +        self.vg.deactivate_lv(volume.name)
deactivate_lv 是在 commit 314611f79afa6fe79f3d5022c814772048669bb0 中增加的，目前 cinder.brick.local_dev.lvm.LVM 没有这个方法。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/drivers/rbd.py
> +    def revert_to_snapshot(self, context, volume, snapshot):
这个实现上游虽然没有合并，但是也是可以 cherry-pick 的，保留原始 commit 信息比较好。

如果保留原始 commit 信息，支持 revert 到任意 snapshot 是我们自己单独实现的，可以单独抽离出来作为第 3 个 commit 。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +    def _create_snapshot_in_db(self, context,
这个函数大部份内容都是不需要的（状态校验这些在 api 应该都已经做完了），只保留创建 snapshot 的 options 以及 db.snapshot_create （db.snapshot_create 也不需要捕获异常）即可，最后和 _create_backup_snapshot 合并一个函数即可。这样就和上游的实现是一样的了。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +        support_reverting_to_any = False
1. 这个属性可以更明确一些，比如 support_reverting_to_any_snapshot ；
2. 这个属性为保持和上游实现的兼容，应该直接在 cinder.volume.driver.VolumeDriver 里增加为一个类属性，默认值为 False ，在 cinder.volume.drivers.rbd.RBDDriver 里设置为 True 就是对父类的覆盖。这样这里的代码只需要简单的判断是 self.support_reverting_to_any_snapshot 是不是 True 就可以了。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +            backup_snapshot = self._create_backup_snapshot(context, volume)
_creaet_backup_snapshot 和 _revert_to_snapshot 合到一个 try...except 里即可，和上游保持一致。分开的话，重复的代码比较多，因为 2 者任何一个出错，清理过程都是一样：

1. 发送 end 的 notification ；
2. 还原卷的状态；
~3. 删除临时快照。（这一步上游的代码好像是有点问题，可以加单独的 commit 修复）~
最后这一步不对，上游的实现是对的，临时快照本来是为了出问题时，手动恢复卷准备的，所以出现异常时，不能自动删除，只能人工检查后，再决定是否需要删除。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +            if volume['size'] != snapshot['size']:
这里的处理看起来有问题，按照 cinder/volume/driver.py 里 revert_to_snapshot 函数的注释，revert 是不改变 volume 的大小的，这种设计是合理的：

1. Cinder 里卷的大小只会扩大，不会缩小；
2. 如果卷的大小改变需要更新租户的 quota 使用量，增加复杂度；
3. 如果快照的大小比卷更大，为了防止数据丢失，应该拒绝 revert ；不过由于第 1 条的原因，不会出现快照比卷大的情况，所以不用考虑这种情况；
4. 如果快照的大小比卷更小，driver 在 revert 时把卷的大小变小（ rbd 即是这种情况），需要 rbd driver 里把卷的大小改回原来的大小（这一点上游待合并的 commit 没考虑到，我也去提了一个 comment ）

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +            raise exception.BadResetResourceStatus(message=msg)
噢，之前没有理解这个新增的 BadResetResourceStatus 的作用，这个是新版本在 update 数据库时增加的功能，即修改数据库会再次校验数据库对象的状态，这个功能现在版本没有，所以这个 Exception 看起来暂时没什么必要。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +            self.db.snapshot_update(context, snapshot['id'],
之前提过，更新数据库对象可以不对异常进行捕获。

2017-09-04 07:19 UTC, zhaochao commented on cinder/volume/manager.py
> +            self.delete_snapshot(context, backup_snapshot['id'])
上游 commit 里，delete_snapshot 里关于 quota 的处理需要 backport ，即创建临时快照，不能占用 quota ，删除临时快照时相应的也不能对 quota 进行变动。

2017-09-05 02:06 UTC, wwba commented on cinder/api/contrib/volume_actions.py
> +        params = body['os-revert']
没有直接掉is_valid_body（）有两个方面原因：
１，上游代码显示地raise HTTPBadRequest异常，＂params = body['os-revert']＂可能会抛出异常,后面＂snapshot_id = params.get("snapshot_id", None)＂才需要检查返回值；
２，参考_volume_upload_image()获取params;

此处改一下，捕获异常吧．

2017-09-05 02:24 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        params = body['os-revert']
没，我是说参考别的 action ，比如 os-retype ，直接取 body['os-revert']['snapshot_id'] ，如果出异常，或者取出来是空，都可以算是 BadRequest 。

2017-09-05 02:49 UTC, wwba commented on cinder/api/contrib/volume_actions.py
> +        self.volume_api.revert_to_snapshot(context, volume, snapshot)
上游代码之所以在这里处理InvalidVolume，InvalidSnapshot,VolumeSizeExceedsAvailableQuota,是重新进行了归类然后抛出，VolumeSizeExceedsAvailableQuota异常在这里不会抛出，HTTPConflict也没有必要进行Backport，所以这里捕获异常不是必须的，所有的异常都在api.py中捕获并进行处理即可．

2017-09-05 02:56 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        self.volume_api.revert_to_snapshot(context, volume, snapshot)
不是这样， cinder/volume/api.py 里面的异常不会直接和 HTTP 响应的异常对应，在 cinder/api 里要捕获异常，正是为了把后端的异常转换成前端的 HTTP 响应。

2017-09-05 03:26 UTC, wwba commented on cinder/volume/manager.py
> +        support_reverting_to_any = False
你说的这个我之前想到了．
１，这样设计不随意修改上游cinder.volume.driver.VolumeDriver;
2, 新支持的support_reverting_to_any_snapshot driver才添加support_reverting_to_any_snapshot 属性．

2017-09-05 03:37 UTC, wwba commented on cinder/volume/manager.py
> +            backup_snapshot = self._create_backup_snapshot(context, volume)
_creaet_backup_snapshot 和 _revert_to_snapshot 分开主要是方便调试的目的，creaet_backup_snapshot配额的问题是容易出错的，_revert_to_snapshot 跟后台驱动有关，我觉得还是分开好．

2017-09-05 03:41 UTC, zhaochao commented on cinder/volume/manager.py
> +        support_reverting_to_any = False
那这样倒是也可以，不过感觉没什么必要，毕竟和其它代码之间没有什么关联，直接改应该没什么影响。

2017-09-05 03:43 UTC, wwba commented on cinder/volume/manager.py
> +            if volume['size'] != snapshot['size']:
这个２和４点我都没有考虑到,这里不更新volume size.

2017-09-05 03:56 UTC, zhaochao commented on cinder/volume/manager.py
> +            backup_snapshot = self._create_backup_snapshot(context, volume)
配额的问题后面说过了，这个过程中不要修改。由于 2 个步骤山错处理相同，还是应该合到一起。

2017-09-05 04:00 UTC, wwba commented on cinder/volume/manager.py
> +    def _create_snapshot_in_db(self, context,
原来想封装成一个通用函数（必须进行volume和snapshot的状态检查），看来的确没有必要，这部分代码在_create_backup_snapshot中实现即可， 同时去掉配额管理．

2017-09-13 07:12 UTC, zhaochao requested changes

2017-09-13 07:12 UTC, zhaochao commented on cinder/brick/local_dev/lvm.py
> +            LOG.error(_LE('StdErr  :%s'), err.stderr)
`_LE` 这个没 import ，可以和这个文件其它地方保持一致只用 `_` 。

2017-09-13 07:12 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        db = importutils.import_module(db_driver)
这里应该直接在文件开头 from cinder import db 就行。

2017-09-13 07:12 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +                                                        volume['id'])
db.snapshot_get_latest_for_volume 可能出现 VolumeSnapshotNotFound ，需要捕获。

2017-09-13 07:12 UTC, zhaochao commented on cinder/exception.py
> +class BadResetResourceStatus(CinderException):
这个在当前的 Cinder 版本里用不上，可以去掉。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +        snapshot = None
上面这一行多余了。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +        2.2. try the generic way to revert volume if driver's method is missing
generic way 相关的代码去掉了，这里注释也可以改了，最终在 commit msg 里也说明一下。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +                                  {'status': 'available'})
这个地方还有点问题，应该是：
如果 volume 的状态不是 reverting ，中止操作，把 snapshot 的状态改为 available ，因为在 api 那里把 snapshot 改成 restoring 了。

这里改 volume 的状态是不对，因为已经发现 volume 的状态发生变化，不符合预期的 'reverting' 。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +                                    {'status': 'available'})
同样这里也要改成：
如果 snapshot 的预期状态不对，应该中止操作，把 snapshot 的状态改成 error_restoring 之类的状态（这个状态的确是之前没有），同时把 volume 的状态改回 available （因为前面已经检查过 volume 的状态是 reverting ，说明是这个操作改动的，出错的话，得改回去）。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +                if backup_snapshot:
这里如果要在日志提醒 backup_snapshot 创建成功的话，可以放到这个异常处理的最后，在 msg 里加上，说明 backup_snapshot 已经创建成功。

不过其实意义不大。目前的实现，这个 backup_snapshot 创建成功之后只能手工想办法删除，没有可供调用的 api 来完成，最终是要人工手动处理。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +                else:
这里就不是 else 了，因为上面出错了， revert 这个操作就失败了，下面这个 msg 是基本内容。

2017-09-13 07:12 UTC, zhaochao commented on cinder/volume/manager.py
> +                                      {'status': 'error'})
这里也要同时处理 snapshot 的状态，改成 error_restoring 或者 available 。

2017-09-13 07:39 UTC, zhaochao commented on cinder/volume/manager.py
> +            snapshot_db = self.db.snapshot_get_latest_for_volume(context,
snapshot_db 这种变量名不太好，可以用上游的 l_snap 。

2017-09-13 07:39 UTC, zhaochao commented on cinder/volume/manager.py
> +                                        {'status': 'available'})
这里也得还原 volume 的状态。

2017-09-13 11:33 UTC, wwba commented on cinder/volume/manager.py
> +                if backup_snapshot:
日志记录create_snapshot delete_snapshot执行完成后都会打印，这里的确不需要判断backup_snapshot的值．

2017-09-13 12:11 UTC, wwba commented on cinder/volume/manager.py
> +                                  {'status': 'available'})
这里不能改snapshot的状态，可以是除开restoring的另外一种状态，参考restore_backup， 这个是cinder-volume来做的，其实这里只需要将volume置为error状态，backup available即可（只读)

2017-09-18 02:32 UTC, zhaochao commented on cinder/brick/local_dev/lvm.py
> +            LOG.exception(_LE('Error deactivating LV'))
这里还留了一个 ``_LE``

2017-09-18 02:32 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +        db = importutils.import_module(db_driver)
这里还没改，虽然这一部份后面的 commit 会去掉，但是还是要改下。

2017-09-18 02:32 UTC, zhaochao commented on cinder/api/contrib/volume_actions.py
> +                                                        volume['id'])
这里和上面 import db 一样，也需要改。变量名应该直接用上游 commit 里的 l_snap 。

2017-09-18 08:46 UTC, zhaochao commented on cinder/volume/manager.py
> +                                  {'status': 'error_reverting'})
revert 操作失败之后，volume 和 snapshot 的状态设置，需要确定一个基本原则。

另外一个小问题是，每次调 volume_update 和 snapshot_update ，可以让它们的顺序保持一致。

2017-09-18 08:46 UTC, zhaochao commented on cinder/volume/manager.py
> +        self._notify_about_snapshot_usage(context, snapshot, "revert.end")
revert.end 应该单独加一个 finally 这样的处理比较好。

2017-09-18 10:48 UTC, merged